Revert "Keep UTC time zone attached to datetime objects when API returns timestamps in UTC."
This reverts commit 02c9c844899247d24fb5a85780d80df4edd8a629.

Throws the following exception on Enyaq for Webspider:

```
Traceback (most recent call last):
  File "/home/nivo/dev/skodaconnect/example/me.py", line 358, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/nivo/dev/skodaconnect/example/me.py", line 247, in main
    print(f'\tstr_state: {instrument.str_state} - state: {instrument.state}')
  File "/home/nivo/dev/skodaconnect/skodaconnect/dashboard.py", line 123, in str_state
    return f'{self.state}'
  File "/home/nivo/dev/skodaconnect/skodaconnect/dashboard.py", line 127, in state
    val = super().state
  File "/home/nivo/dev/skodaconnect/skodaconnect/dashboard.py", line 58, in state
    if hasattr(self.vehicle, self.attr):
  File "/home/nivo/dev/skodaconnect/skodaconnect/vehicle.py", line 1542, in last_connected
    last_connected = datetime.fromisoformat(last_connected_utc)
ValueError: Invalid isoformat string: '2023-12-11T15:34:24.425Z'
```